language: objective-c

branches:
 only:
 - develop
 - travis-ci

xcode_project: TVConference.xcodeproj
xcode_scheme:  TVConference
osx_image:     xcode7.1
xcode_sdk:     appletvsimulator9.0

script:
- xcodebuild clean build test -sdk appletvsimulator9.0 -project TVConference.xcodeproj -scheme TVConference