language: objective-c

branches:
 only:
 - develop
 - travis-ci
 
notifications:
  slack: minusetcortex:ljbtq8hQFgPVihrDXsLBB3JB

osx_image:     xcode7.1
xcode_project: TVConference.xcodeproj
xcode_scheme:  TVConference
xcode_sdk:     appletvsimulator9.0

script:
- xcodebuild clean build test -sdk appletvsimulator9.0 -project TVConference.xcodeproj -scheme TVConference